=== ywfyywq/xmlparse-demo/dtd/menu.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ENTITY writer "Jack Yu">
<!ENTITY copyright "Copyright www.xyz0751.com">

<!ELEMENT breakfast_menu (food)*>
<!ELEMENT food (name, price, description, calories)>
<!ATTLIST food
        id CDATA #REQUIRED
        >

<!ELEMENT name      (#PCDATA)>
<!ELEMENT price    (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT calories    (#PCDATA)>

=== ywfyywq/xmlparse-demo/src/main/resources/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE breakfast_menu PUBLIC "-//localhost//DTD Config 3.0//EN"
        "dtd/menu.dtd" >

<breakfast_menu>
    <food id="1">
        <name>Belgian Waffles</name>
        <price>$5.95</price>
        <description>
            two of our famous Belgian Waffles with plenty of real maple syrup
        </description>
        <calories>650</calories>
    </food>
    <food id="2">
        <name>Strawberry Belgian Waffles</name>
        <price>$7.95</price>
        <description>
            light Belgian waffles covered with strawberries and whipped cream
        </description>
        <calories>900</calories>
    </food>
    <food id="3">
        <name>Berry-Berry Belgian Waffles</name>
        <price>$8.95</price>
        <description>
            light Belgian waffles covered with an assortment of fresh berries and whipped cream
        </description>
        <calories>900</calories>
    </food>
    <food id="4">
        <name>French Toast</name>
        <price>$4.50</price>
        <description>
            thick slices made from our homemade sourdough bread
        </description>
        <calories>600</calories>
    </food>
    <food id="5">
        <name>Homestyle Breakfast</name>
        <price>$6.95</price>
        <description>
            two eggs, bacon or sausage, toast, and our ever-popular hash browns
        </description>
        <calories>950</calories>
    </food>
</breakfast_menu>
